### ISSUE TITLE
Support of TYPO3 7.6

### ISSUE THREAD

**Issue by sabbelasichon** [Skyfillers/sf_simple_faq#55]
Hi there,
first of all, thanks for this neat extension. 

Are you planning to support TYPO3 Version 7.6 as well? Are you interested in a pull request which supports both TYPO3 6.2 and 7.6?

**Comment by machwatt** [comment]
Hi @sabbelasichon 
sure why not :)

**Comment by Konafets** [comment]
Done in #656d44d
